### ISSUE TITLE
Training without proxy labels on custom dataset

### ISSUE THREAD

**Issue by sieme97** [fabiotosi92/monoResMatch-Tensorflow#8]
Training from scratch without proxy labels produce very bad results.  Why is it so?
Do I have to change the max disp value in correlation map?

**Comment by fabiotosi92** [comment]
Hi, in order to properly train the network using the photometric image loss only you should change the activation function of each prediction layer using a sigmoid (as in Monodepth1, Godard et al). Moreover, you should also replace our bilinear sampler function with this one: https://github.com/mrharicot/monodepth/blob/master/bilinear_sampler.py

**Comment by fabiotosi92** [comment]
Hi, in order to properly train the network using the photometric image loss only you should change the activation function of each prediction layer using a sigmoid (as in Monodepth1, Godard et al). Moreover, you should also replace our bilinear sampler function with this one: https://github.com/mrharicot/monodepth/blob/master/bilinear_sampler.py

**Comment by sieme97** [comment]
Alright, thanks

**Comment by msceme** [comment]
Alright, thanks

**Comment by sieme97** [comment]
Alright, thanks

> Hi, in order to properly train the network using the photometric image loss only you should change the activation function of each prediction layer using a sigmoid (as in Monodepth1, Godard et al). Moreover, you should also replace our bilinear sampler function with this one: https://github.com/mrharicot/monodepth/blob/master/bilinear_sampler.py

I have changed the disparity prediction layer activation function and the bilinear sampler, but the training is still not going well.

**Comment by fabiotosi92** [comment]
Try to disable the "crop" approach by setting 'patch_width' and 'patch_height' to the same size of 'width' and 'height'. Our choice to crop images is well suited for proxies but not for the photometric loss alone.

**Comment by sieme97** [comment]
The issue has been resolved after applying sigmoid actiavation on only disparity refinement layers, and relu on initial disparity layers.
